<a href="https://colab.research.google.com/github/kujiancheng/Data_Science_W1/blob/main/TutorialW3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

array_2x2 = np.array([[1, 2],
                      [3, 4]])
print("2x2 Array:\n", array_2x2)

2x2 Array:
 [[1 2]
 [3 4]]


In [8]:
random_3x4 = np.random.rand(3, 4)
print("\n Random 3x4 Array:\n", random_3x4)


 Random 3x4 Array:
 [[0.52246798 0.80719908 0.72615322 0.76542473]
 [0.37816695 0.6187795  0.60186403 0.69050761]
 [0.66216107 0.83674745 0.45914091 0.98770486]]


In [9]:
ones_array = np.ones((2, 3))
zeros_array = np.zeros((2, 3))
print("\n Array of Ones:\n", ones_array)
print("Array of Zeroes:\n", zeros_array)


 Array of Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Array of Zeroes:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
random_6x3 = np.random.rand(6, 3)
transpose_array = random_6x3.T
print("\n Random 6x3 Array:\n", random_6x3)
print("Transposed Array (3x6):\n", transpose_array)


 Random 6x3 Array:
 [[0.96931409 0.38019585 0.08962803]
 [0.48012024 0.7324569  0.50591763]
 [0.17410528 0.29220748 0.23096252]
 [0.06870298 0.54446499 0.58495025]
 [0.43111962 0.38545036 0.01734021]
 [0.47431709 0.87730271 0.48222629]]
Transposed Array (3x6):
 [[0.96931409 0.48012024 0.17410528 0.06870298 0.43111962 0.47431709]
 [0.38019585 0.7324569  0.29220748 0.54446499 0.38545036 0.87730271]
 [0.08962803 0.50591763 0.23096252 0.58495025 0.01734021 0.48222629]]


In [11]:
n, p, m = 2, 3, 4
A = np.random.rand(n, p)
B = np.random.rand(p, m)
dot_product = np.dot(A, B)

print("\n Matrix A (n x p):\n", A)
print("Matrix B (p x m):\n", B)
print("Dot Product (n x m):\n", dot_product)


 Matrix A (n x p):
 [[0.69182602 0.9178307  0.76668801]
 [0.86473462 0.22878493 0.44954789]]
Matrix B (p x m):
 [[0.12595499 0.6284546  0.77480593 0.71852072]
 [0.51403207 0.92552279 0.17879739 0.40422857]
 [0.07385174 0.42139681 0.21719375 0.28912154]]
Dot Product (n x m):
 [[0.61555459 1.60733435 0.86665648 1.08977074]
 [0.25972032 0.94463017 0.80854665 0.84378512]]
